name: Tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        if: success()
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run builder unit tests
        if: success()
        run: |
          python -m nose2 -s scripts/builder
